language: cpp
sudo: false
os:
  - linux
  - osx
env:
  matrix:
    - export NODE_VERSION=v0.10
    - export NODE_VERSION=v0.12
    - export NODE_VERSION=v4.0
before_install:
  - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.26.1/install.sh | bash
  - nvm install $NODE_VERSION
  - nvm use $NODE_VERSION
script:
  - npm install
  - npm test
